# Generated by Django 5.0.1 on 2025-10-03 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('encargado', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_control', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_productividad', models.DecimalField(decimal_places=2, help_text='Valor entre 0 y 1 (ejemplo: 0.75 = 75%)', max_digits=5)),
                ('lugar', models.CharField(max_length=200)),
                ('fecha_estimacion_culminacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.cliente')),
                ('consumibles', models.ManyToManyField(blank=True, to='inventario.consumible')),
                ('stock_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_almacen', to='inventario.stock')),
                ('stock_comprar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_comprar', to='inventario.stock')),
            ],
        ),
    ]
