# Generated by Django 5.2.8 on 2026-03-15 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_reporte', models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal'), ('diario', 'Diario'), ('personalizado', 'Personalizado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
