# Generated by Django 5.0.1 on 2025-11-07 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_taza_pesos_dolares_valor'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='consumibles',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='epps',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='stock_almacen',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='stock_comprar',
        ),
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('por_entregar', 'Por entregar'), ('ejecutado', 'Ejecutado')], default='borrador', help_text='Estado actual del reporte en el flujo de ejecución', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='aprobado',
            field=models.BooleanField(default=False, help_text='Indica si el presupuesto fue aprobado'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='n_control',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='porcentaje_productividad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='presupuesto_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='APU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rendimiento', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_herramientas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_logistica', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('administracion_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apus', to='reportes.reporte')),
            ],
        ),
        migrations.CreateModel(
            name='APUItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('mano_obra', 'Mano de obra'), ('herramienta', 'Herramienta'), ('logistica', 'Logística')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('desperdicio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reportes.apu')),
                ('consumible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.consumible')),
                ('epp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.epp')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.stock')),
            ],
        ),
    ]
