# Generated by Django 5.0.1 on 2025-10-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rif',
            field=models.CharField(default='PENDIENTE', max_length=20, unique=True),
        ),
    ]
