# Generated by Django 5.0.1 on 2025-10-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
        ('reportes', '0002_cliente_rif'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_inicio', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Configuración de Reportes',
                'verbose_name_plural': 'Configuración de Reportes',
            },
        ),
        migrations.AlterField(
            model_name='reporte',
            name='n_control',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='stock_almacen',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='stock_comprar',
        ),
        migrations.AddField(
            model_name='reporte',
            name='stock_almacen',
            field=models.ManyToManyField(blank=True, related_name='reportes_almacen', to='inventario.stock'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='stock_comprar',
            field=models.ManyToManyField(blank=True, related_name='reportes_comprar', to='inventario.stock'),
        ),
    ]
