# Generated by Django 5.0.1 on 2025-11-15 02:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_consumible_options_alter_consumible_descipcion_and_more'),
        ('reportes', '0002_remove_reporte_consumibles_remove_reporte_epps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APUHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('depreciacion_hora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Depreciación por hora', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_herramienta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='APULogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_logistica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='APUManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='APUMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('desperdicio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desperdicio en % o unidad que definas', max_digits=6)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_material', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='apuitem',
            name='apu',
        ),
        migrations.RemoveField(
            model_name='apuitem',
            name='consumible',
        ),
        migrations.RemoveField(
            model_name='apuitem',
            name='epp',
        ),
        migrations.RemoveField(
            model_name='apuitem',
            name='stock',
        ),
        migrations.AlterModelOptions(
            name='apu',
            options={'ordering': ['reporte', 'numero'], 'verbose_name': 'APU', 'verbose_name_plural': 'APUs'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion', '-id'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.RenameField(
            model_name='apu',
            old_name='administracion_gastos',
            new_name='precio_unitario',
        ),
        migrations.RenameField(
            model_name='apu',
            old_name='costo_herramientas',
            new_name='total_base',
        ),
        migrations.RenameField(
            model_name='apu',
            old_name='costo_logistica',
            new_name='total_herramientas',
        ),
        migrations.RenameField(
            model_name='apu',
            old_name='costo_mano_obra',
            new_name='total_logistica',
        ),
        migrations.RenameField(
            model_name='apu',
            old_name='costo_materiales',
            new_name='total_mano_obra',
        ),
        migrations.RenameField(
            model_name='apu',
            old_name='total_unitario',
            new_name='total_materiales',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='observaciones',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='apu',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='apu',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='apu',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='apu',
            name='utilidad',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_estimacion_culminacion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='n_control',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='porcentaje_productividad',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='presupuesto_estimado',
        ),
        migrations.AddField(
            model_name='apu',
            name='bono_alimenticio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='15$ por día por cada trabajador', max_digits=12),
        ),
        migrations.AddField(
            model_name='apu',
            name='costo_directo_por_unidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo por unidad + costo total herramientas + costo total materiales', max_digits=12),
        ),
        migrations.AddField(
            model_name='apu',
            name='costo_por_unidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prestaciones sociales / rendimiento', max_digits=12),
        ),
        migrations.AddField(
            model_name='apu',
            name='depreciacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Depreciación general del APU (si aplica)', max_digits=6),
        ),
        migrations.AddField(
            model_name='apu',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apu',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='apu',
            name='gastos_administrativos_15',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='15% de gastos administrativos', max_digits=12),
        ),
        migrations.AddField(
            model_name='apu',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apu',
            name='prestaciones_sociales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total mano de obra * 200', max_digits=12),
        ),
        migrations.AddField(
            model_name='apu',
            name='total_apu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal + utilidad', max_digits=12),
        ),
        migrations.AddField(
            model_name='apu',
            name='utilidad_15',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='15% de utilidad sobre el subtotal', max_digits=12),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='n_presupuesto',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True, verbose_name='Número de presupuesto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='total_reporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de total_apu de todos los APUs del reporte', max_digits=14),
        ),
        migrations.AlterField(
            model_name='apu',
            name='rendimiento',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Valor entre 0 y 1', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apu',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo directo por unidad + gastos administrativos', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apu',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='apu',
            constraint=models.UniqueConstraint(fields=('reporte', 'numero'), name='unique_apu_numero_por_reporte'),
        ),
        migrations.AddField(
            model_name='apuherramienta',
            name='apu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='reportes.apu'),
        ),
        migrations.AddField(
            model_name='apulogistica',
            name='apu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logisticas', to='reportes.apu'),
        ),
        migrations.AddField(
            model_name='apumanoobra',
            name='apu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manos_obra', to='reportes.apu'),
        ),
        migrations.AddField(
            model_name='apumaterial',
            name='apu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='reportes.apu'),
        ),
        migrations.AddField(
            model_name='apumaterial',
            name='consumible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.consumible'),
        ),
        migrations.AddField(
            model_name='apumaterial',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.stock'),
        ),
        migrations.DeleteModel(
            name='APUItem',
        ),
    ]
