# Generated by Django 5.0.1 on 2025-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_proveedor_consumibles_remove_proveedor_epps_and_more'),
        ('reportes', '0003_reporteconfig_alter_reporte_n_control_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AddField(
            model_name='reporte',
            name='epps',
            field=models.ManyToManyField(blank=True, related_name='reportes_epps', to='inventario.epp'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='consumibles',
            field=models.ManyToManyField(blank=True, related_name='reportes_consumibles', to='inventario.consumible'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='n_control',
            field=models.CharField(editable=False, help_text='Número de control autogenerado secuencial.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reporteconfig',
            name='punto_inicio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
