# Generated by Django 5.2.8 on 2025-11-17 17:05

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_apu_bono_alimenticio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apu',
            options={'ordering': ['reporte', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion', '-id']},
        ),
        migrations.AlterField(
            model_name='apu',
            name='depreciacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='apu',
            name='rendimiento',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='n_presupuesto',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='total_reporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
