# Generated by Django 5.2.8 on 2025-11-17 17:09

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_apu_options_alter_reporte_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apu',
            options={'ordering': ['reporte', 'numero'], 'verbose_name': 'APU', 'verbose_name_plural': 'APUs'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion', '-id'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterField(
            model_name='apu',
            name='bono_alimenticio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='15$ por día por cada trabajador', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apu',
            name='costo_directo_por_unidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo por unidad + costo total herramientas + costo total materiales', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apu',
            name='costo_por_unidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prestaciones sociales / rendimiento', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apu',
            name='depreciacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Depreciación general del APU (si aplica)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='apu',
            name='gastos_administrativos_15',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='15% de gastos administrativos', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apu',
            name='prestaciones_sociales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total mano de obra * 200', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apu',
            name='rendimiento',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Valor entre 0 y 1', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apu',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo directo por unidad + gastos administrativos', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apu',
            name='total_apu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal + utilidad', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apu',
            name='utilidad_15',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='15% de utilidad sobre el subtotal', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apuherramienta',
            name='depreciacion_hora',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Depreciación por hora', max_digits=10),
        ),
        migrations.AlterField(
            model_name='apumaterial',
            name='desperdicio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desperdicio en % o unidad que definas', max_digits=6),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='n_presupuesto',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de presupuesto'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='total_reporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de total_apu de todos los APUs del reporte', max_digits=14),
        ),
    ]
