# Generated by Django 5.2.8 on 2025-11-17 17:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_alter_apu_options_alter_reporte_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apumaterial',
            name='desperdicio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de desperdicio individual del material', max_digits=6),
        ),
    ]
