# Generated by Django 5.2.8 on 2025-11-17 18:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_alter_apumaterial_desperdicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='apu',
            name='presupuesto_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Presupuesto base calculado o asignado manualmente', max_digits=12),
        ),
    ]
