# Generated by Django 5.2.8 on 2025-11-17 18:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_apu_presupuesto_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='apu',
            name='presupuesto_con_desp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Presupuesto base considerando la depreciación (%) del APU', max_digits=12),
        ),
    ]
