# Generated by Django 5.2.8 on 2025-11-19 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_apu_presupuesto_con_desp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text="Título corto de la nota (ej: 'Ajuste de precios', 'Pendiente de aprobación')", max_length=150, null=True)),
                ('descripcion', models.TextField(help_text='Detalle de la nota asociada al reporte')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='reportes.reporte')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
