# Generated by Django 5.2.8 on 2025-11-19 23:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_notareporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apu',
            name='rendimiento',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Valor de rendimiento (sin límite de rango)', max_digits=12),
        ),
    ]
