# Generated by Django 6.0.3 on 2026-03-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0011_alter_apu_rendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='apu',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'En espera'), ('APROBADO', 'Aprobado'), ('CANCELADO', 'Cancelado')], default='ESPERA', help_text='Estado actual de aprobación del APU', max_length=10),
        ),
    ]
