# Generated by Django 6.0.3 on 2026-03-31 22:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_apu_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'En espera'), ('RECHAZADO', 'Rechazado'), ('APROBADO_ESPERA', 'Aprobado a espera de ejecución'), ('EJECUTADO', 'Ejecutado'), ('EJECUTADO_POR_PAGAR', 'Ejecutado Por pagar'), ('EJECUTADO_PAGADO', 'Ejecutado Pagado')], default='ESPERA', help_text='Estado detallado del ciclo de vida del reporte', max_length=300),
        ),
        migrations.AlterField(
            model_name='apu',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'En espera'), ('RECHAZADO', 'Rechazado'), ('APROBADO_ESPERA', 'Aprobado a espera de ejecución'), ('EJECUTADO', 'Ejecutado'), ('EJECUTADO_POR_PAGAR', 'Ejecutado Por pagar'), ('EJECUTADO_PAGADO', 'Ejecutado Pagado')], default='ESPERA', help_text='Estado actual de aprobación del APU', max_length=30),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='total_reporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de total_apu de todos los APUs vinculados', max_digits=14),
        ),
    ]
