# Generated by Django 5.2.8 on 2026-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_reporte_estado_alter_apu_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='orden_servicio',
            field=models.CharField(blank=True, help_text='Número de orden de servicio (opcional)', max_length=50, null=True, verbose_name='Orden de Servicio'),
        ),
    ]
