# Generated by Django 5.2.8 on 2026-04-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0014_add_orden_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apu',
            name='estado',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('APROBADO_ESPERA', 'Aprobado en espera de ejecución'), ('EJECUTADO', 'Ejecutado'), ('PAGADO', 'Pagado')], default='EN_ESPERA', help_text='Estado detallado del ciclo de vida del reporte', max_length=300),
        ),
    ]
