# Generated by Django 5.2.8 on 2026-04-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0015_actualizar_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('EN_ESPERA', 'En espera'), ('APROBADO_ESPERA', 'Aprobado en espera de ejecución'), ('EJECUTADO', 'Ejecutado'), ('PAGADO', 'Pagado')], max_length=30, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('APROBADO_ESPERA', 'Aprobado en espera de ejecución'), ('EJECUTADO', 'Ejecutado'), ('PAGADO', 'Pagado')], max_length=30, verbose_name='Estado nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
