# Generated by Django 5.2.8 on 2026-04-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0016_historial_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadoreporte',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('EN_ESPERA', 'En espera'), ('APROBADO_ESPERA', 'Aprobado en espera de ejecución'), ('EJECUTADO', 'Ejecutado'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], max_length=30, null=True, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='historialestadoreporte',
            name='estado_nuevo',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('APROBADO_ESPERA', 'Aprobado en espera de ejecución'), ('EJECUTADO', 'Ejecutado'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], max_length=30, verbose_name='Estado nuevo'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('APROBADO_ESPERA', 'Aprobado en espera de ejecución'), ('EJECUTADO', 'Ejecutado'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='EN_ESPERA', help_text='Estado detallado del ciclo de vida del reporte', max_length=300),
        ),
    ]
