# Generated by Django 5.2.8 on 2026-04-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0017_agregar_estado_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha_estimacion_culminacion',
            field=models.DateField(blank=True, help_text='Fecha estimada de culminación del proyecto', null=True, verbose_name='Fecha de culminación'),
        ),
    ]
