# Generated by Django 6.0.3 on 2026-04-27 20:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0018_agregar_fecha_culminacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_nota', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de nota de entrega')),
                ('codigo_alfa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código alfa')),
                ('cliente_nombre', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de entrega')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_entrega', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Nota de Entrega',
                'verbose_name_plural': 'Notas de Entrega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotaEntregaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apu_descripcion', models.TextField(verbose_name='Descripción del APU')),
                ('cantidad_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cantidad total del APU')),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cantidad entregada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nota_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reportes.notaentrega')),
            ],
            options={
                'verbose_name': 'Item de Nota de Entrega',
                'verbose_name_plural': 'Items de Notas de Entrega',
            },
        ),
    ]
