# Generated by Django 6.0.3 on 2026-04-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0019_notaentrega_notaentregaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaentregaitem',
            name='apu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='reportes.apu', verbose_name='APU'),
        ),
    ]
