# Generated by Django 6.0.3 on 2026-04-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0020_notaentregaitem_apu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaentrega',
            name='codigo_alfa',
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Compra'),
        ),
    ]
