# Generated by Django 6.0.3 on 2026-04-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0021_remove_notaentrega_codigo_alfa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaentrega',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Nota'),
        ),
    ]
