# Generated by Django 6.0.3 on 2026-04-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0022_notaentrega_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaentrega',
            name='con_monto',
            field=models.BooleanField(default=True, verbose_name='¿Lleva monto?'),
        ),
    ]
