# Generated by Django 6.0.3 on 2026-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0023_notaentrega_con_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaentrega',
            name='con_monto',
        ),
        migrations.AlterField(
            model_name='apu',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción', null=True),
        ),
    ]
