# Generated by Django 6.0.3 on 2026-06-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0024_remove_notaentrega_con_monto_alter_apu_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='forma_pago',
            field=models.CharField(blank=True, default='60% ANTICIPO  40% A SU ENTREGA', max_length=200, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='terminos_condiciones',
            field=models.TextField(blank=True, default='LOS PRECIOS NO INCLUYEN IVA; LO QUE NO ENCUENTRE EN EL PRESENTE PRESUPUESTO SERÁ PRESUPUESTADO POR APARTE.', null=True, verbose_name='Términos y condiciones'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='validez_oferta',
            field=models.CharField(blank=True, default='5 DÍAS', max_length=100, null=True, verbose_name='Validez de la oferta'),
        ),
    ]
