# Generated by Django 6.0.3 on 2026-07-24 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0025_reporte_forma_pago_reporte_terminos_condiciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apu',
            name='porcentaje_administracion',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje de gastos administrativos (ej: 15.00 = 15%)', max_digits=5),
        ),
    ]
