# Generated by Django 6.0.3 on 2026-07-24 15:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0026_apu_porcentaje_administracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='descripcion_descuento',
            field=models.CharField(blank=True, help_text='Razón o concepto del descuento (opcional)', max_length=255, null=True, verbose_name='Descripción del descuento'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado al total del presupuesto (0-99%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='total_reporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de total_apu de todos los APUs vinculados (con descuento aplicado si existe)', max_digits=14),
        ),
    ]
