# Generated by Django 6.0.3 on 2026-07-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0027_reporte_descripcion_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apulogistica',
            name='empleados',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de empleados para este item (solo informativo, no afecta cálculos)'),
        ),
    ]
