# Generated by Django 5.2.8 on 2026-08-06 15:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0028_apulogistica_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apumanoobra',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.00'), max_digits=10),
        ),
    ]
