# Generated by Django 5.2.8 on 2026-08-21 23:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0029_alter_apumanoobra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apulogistica',
            name='empleados',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad de empleados para este item (solo informativo, no afecta cálculos)', max_digits=6),
        ),
    ]
