# Generated by Django 6.0.3 on 2026-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0030_alter_apulogistica_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
    ]
