# Generated by Django 6.0.3 on 2026-09-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0031_alter_cliente_correo_electronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='notas_admin',
            field=models.TextField(blank=True, help_text='Notas internas del administrador. No se renderizan en PDF ni Excel.', null=True, verbose_name='Notas Admin'),
        ),
    ]
