# Generated by Django 6.0.3 on 2026-09-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0032_reporte_notas_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='forma_pago',
            field=models.TextField(blank=True, default='60% ANTICIPO  40% A SU ENTREGA', null=True, verbose_name='Forma de pago'),
        ),
    ]
