# Generated by Django 5.2.8 on 2026-08-19 21:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0029_alter_apumanoobra_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='A', help_text='Prefijo del número de control (ej: A → A-0001)', max_length=10, verbose_name='Serie')),
                ('punto_inicio', models.PositiveIntegerField(blank=True, help_text='Número desde el que empieza la secuencia', null=True, verbose_name='Punto de inicio')),
            ],
            options={
                'verbose_name': 'Configuración de Facturas',
                'verbose_name_plural': 'Configuración de Facturas',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(editable=False, max_length=10)),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('n_factura', models.CharField(editable=False, help_text='Formato Serie-NNNN (ej: A-0001)', max_length=30, unique=True, verbose_name='Número de factura')),
                ('fecha', models.DateField(verbose_name='Fecha de factura')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('BS', 'Bolívares (Bs)')], default='USD', max_length=3, verbose_name='Moneda')),
                ('tasa_bs_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa del Banco Central usada al facturar en Bs', max_digits=14, null=True, verbose_name='Tasa Bs/USD')),
                ('fecha_tasa', models.DateField(blank=True, help_text='Fecha de actualización de la tasa BCV', null=True, verbose_name='Fecha de la tasa')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Cliente')),
                ('cliente_rif', models.CharField(blank=True, default='', max_length=20)),
                ('cliente_encargado', models.CharField(blank=True, default='', max_length=150)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('cliente_direccion', models.CharField(blank=True, default='', max_length=255)),
                ('cliente_correo', models.EmailField(blank=True, default='', max_length=254)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=20, verbose_name='Estado')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='% IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de IVA editable, se suma al total', max_digits=14, verbose_name='Monto IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='reportes.reporte', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apu_descripcion', models.TextField(verbose_name='Descripción')),
                ('unidad', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio unitario')),
                ('total_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_items', to='reportes.apu', verbose_name='APU')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('serie', 'numero'), name='unique_serie_numero_factura'),
        ),
    ]
