# Generated by Django 5.2.8 on 2026-08-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_control',
            field=models.CharField(blank=True, default='', help_text='Número de control (SENIAT) de la factura', max_length=50, verbose_name='Número de control'),
        ),
    ]
