# Generated by Django 5.2.8 on 2026-08-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_numero_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='numero_control',
        ),
        migrations.AddField(
            model_name='factura',
            name='orden_servicio',
            field=models.CharField(blank=True, default='', help_text='Número de orden de servicio asociado a la factura', max_length=50, verbose_name='Orden de servicio'),
        ),
    ]
