# Generated by Django 5.2.8 on 2026-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_factura_numero_control_factura_orden_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='orden_control',
            field=models.CharField(blank=True, default='', help_text='Número de orden de control asociado a la factura', max_length=50, verbose_name='Orden de control'),
        ),
    ]
