# Generated by Django 5.2.8 on 2026-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_orden_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='factura_completa',
            field=models.BooleanField(default=False, editable=False, help_text='True si la factura se emitió por el monto total del presupuesto (modo descripción completa).', verbose_name='Factura completa'),
        ),
    ]
