# Generated by Django 5.2.8 on 2026-08-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_backfill_factura_completa'),
        ('reportes', '0029_alter_apumanoobra_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden del presupuesto dentro de la factura (0 = principal)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_vinculados', to='facturacion.factura', verbose_name='Factura')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_vinculadas', to='reportes.reporte', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Presupuesto de Factura',
                'verbose_name_plural': 'Presupuestos de Factura',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('factura', 'reporte'), name='unique_factura_reporte')],
            },
        ),
    ]
