# Generated by Django 6.0.3 on 2026-09-14 21:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_facturareporte'),
        ('reportes', '0030_alter_apulogistica_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='NC', help_text='Prefijo del número de control (ej: NC → NC-0001)', max_length=10, verbose_name='Serie')),
                ('punto_inicio', models.PositiveIntegerField(blank=True, help_text='Número desde el que empieza la secuencia', null=True, verbose_name='Punto de inicio')),
            ],
            options={
                'verbose_name': 'Configuración de Notas de Crédito',
                'verbose_name_plural': 'Configuración de Notas de Crédito',
            },
        ),
        migrations.CreateModel(
            name='NotaDebitoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='ND', help_text='Prefijo del número de control (ej: ND → ND-0001)', max_length=10, verbose_name='Serie')),
                ('punto_inicio', models.PositiveIntegerField(blank=True, help_text='Número desde el que empieza la secuencia', null=True, verbose_name='Punto de inicio')),
            ],
            options={
                'verbose_name': 'Configuración de Notas de Débito',
                'verbose_name_plural': 'Configuración de Notas de Débito',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(editable=False, max_length=10)),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('n_nota', models.CharField(editable=False, help_text='Formato Serie-NNNN (ej: NC-0001)', max_length=30, unique=True, verbose_name='Número de nota de crédito')),
                ('fecha', models.DateField(verbose_name='Fecha de nota de crédito')),
                ('motivo', models.TextField(blank=True, default='', help_text='Motivo de la nota de crédito', verbose_name='Motivo')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('BS', 'Bolívares (Bs)')], default='USD', max_length=3, verbose_name='Moneda')),
                ('tasa_bs_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Tasa Bs/USD')),
                ('fecha_tasa', models.DateField(blank=True, null=True, verbose_name='Fecha de la tasa')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Cliente')),
                ('cliente_rif', models.CharField(blank=True, default='', max_length=20)),
                ('cliente_encargado', models.CharField(blank=True, default='', max_length=150)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('cliente_direccion', models.CharField(blank=True, default='', max_length=255)),
                ('cliente_correo', models.EmailField(blank=True, default='', max_length=254)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=20, verbose_name='Estado')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='% IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apu_descripcion', models.TextField(verbose_name='Descripción')),
                ('unidad', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio unitario')),
                ('total_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_items', to='reportes.apu', verbose_name='APU')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.notacredito')),
            ],
            options={
                'verbose_name': 'Item de Nota de Crédito',
                'verbose_name_plural': 'Items de Nota de Crédito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(editable=False, max_length=10)),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('n_nota', models.CharField(editable=False, help_text='Formato Serie-NNNN (ej: ND-0001)', max_length=30, unique=True, verbose_name='Número de nota de débito')),
                ('fecha', models.DateField(verbose_name='Fecha de nota de débito')),
                ('motivo', models.TextField(blank=True, default='', help_text='Motivo de la nota de débito', verbose_name='Motivo')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('BS', 'Bolívares (Bs)')], default='USD', max_length=3, verbose_name='Moneda')),
                ('tasa_bs_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Tasa Bs/USD')),
                ('fecha_tasa', models.DateField(blank=True, null=True, verbose_name='Fecha de la tasa')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Cliente')),
                ('cliente_rif', models.CharField(blank=True, default='', max_length=20)),
                ('cliente_encargado', models.CharField(blank=True, default='', max_length=150)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('cliente_direccion', models.CharField(blank=True, default='', max_length=255)),
                ('cliente_correo', models.EmailField(blank=True, default='', max_length=254)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=20, verbose_name='Estado')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='% IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_debito', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Nota de Débito',
                'verbose_name_plural': 'Notas de Débito',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaDebitoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apu_descripcion', models.TextField(verbose_name='Descripción')),
                ('unidad', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio unitario')),
                ('total_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_debito_items', to='reportes.apu', verbose_name='APU')),
                ('nota_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.notadebito')),
            ],
            options={
                'verbose_name': 'Item de Nota de Débito',
                'verbose_name_plural': 'Items de Nota de Débito',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='notacredito',
            constraint=models.UniqueConstraint(fields=('serie', 'numero'), name='unique_serie_numero_nota_credito'),
        ),
        migrations.AddConstraint(
            model_name='notadebito',
            constraint=models.UniqueConstraint(fields=('serie', 'numero'), name='unique_serie_numero_nota_debito'),
        ),
    ]
