# Generated by Django 6.0.3 on 2026-03-31 22:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0012_apu_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto abonado')),
                ('referencia_pago', models.CharField(blank=True, help_text='Opcional: ID de transacción, número de transferencia o cheque', max_length=100, null=True, verbose_name='Número de Referencia')),
                ('fecha_abono', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Abono')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='reportes.reporte', verbose_name='Reporte asociado')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha_abono'],
            },
        ),
    ]
