# Generated by Django 5.2.1 on 2025-05-08 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unidades', models.IntegerField()),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LugarConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('unidades', models.IntegerField()),
                ('monto', models.FloatField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.departamento')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lugarconsumo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('unidades', models.IntegerField()),
                ('monto', models.FloatField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.consumible')),
                ('epp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.epp')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.stock')),
            ],
        ),
    ]
