# Generated by Django 5.2.8 on 2026-03-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('encargado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taza_pesos_dolares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Tasa pesos/dólar actual', max_digits=10)),
            ],
            options={
                'verbose_name': 'Tasa Pesos/Dólares',
                'verbose_name_plural': 'Tasas Pesos/Dólares',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('pza', models.CharField(max_length=50)),
                ('cantidad_disponible', models.IntegerField(default=0, help_text='Cantidad disponible actualmente en inventario')),
                ('costo_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('envio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('costo_5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_15', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_20', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factor_conversion', models.DecimalField(blank=True, decimal_places=4, help_text='Factor usado para calcular mts_ml_m2', max_digits=10, null=True)),
                ('mts_ml_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_fijo', models.BooleanField(default=False, help_text='Indica si es un ítem fijo del sistema.')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.departamento')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('observacion', models.TextField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.stock')),
            ],
        ),
    ]
