# Generated by Django 5.0.1 on 2025-11-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pza',
            field=models.CharField(max_length=50),
        ),
    ]
