# Generated by Django 5.0.1 on 2025-10-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
