# Generated by Django 5.0.1 on 2025-11-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_stock_pza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
