# Generated by Django 5.0.1 on 2025-10-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_proveedor_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='consumible',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='epp',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='stock',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='consumibles',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='inventario.consumible'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='epps',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='inventario.epp'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='inventario.stock'),
        ),
    ]
