# Generated by Django 5.0.1 on 2025-11-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_stock_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taza_pesos_dolares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Tasa pesos/dólar actual', max_digits=10)),
            ],
            options={
                'verbose_name': 'Tasa Pesos/Dólares',
                'verbose_name_plural': 'Tasas Pesos/Dólares',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='costo_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='costo_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
