# Generated by Django 5.0.1 on 2025-10-04 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_proveedor_consumible_remove_proveedor_epp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='consumibles',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='epps',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='stocks',
        ),
        migrations.AddField(
            model_name='consumible',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumibles', to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='epp',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epps', to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='stock',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='inventario.proveedor'),
        ),
    ]
