# Generated by Django 5.0.1 on 2025-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_taza_pesos_dolares_stock_costo_dolares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='mts_ml_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='utilidad_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
