# Generated by Django 5.0.1 on 2025-11-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_stock_mts_ml_m2_alter_stock_utilidad_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='factor_conversion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Factor usado para calcular mts_ml_m2 (costo / factor_conversion)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mts_ml_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
