# Generated by Django 5.0.1 on 2025-11-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_stock_factor_conversion_alter_stock_mts_ml_m2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taza_pesos_dolares',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Tasa pesos/dólar actual', max_digits=10),
        ),
    ]
