# Generated by Django 5.0.1 on 2025-11-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_taza_pesos_dolares_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumible',
            name='item_fijo',
            field=models.BooleanField(default=False, help_text='Indica si es un ítem fijo del sistema.'),
        ),
        migrations.AddField(
            model_name='epp',
            name='item_fijo',
            field=models.BooleanField(default=False, help_text='Indica si es un ítem fijo del sistema.'),
        ),
        migrations.AddField(
            model_name='stock',
            name='item_fijo',
            field=models.BooleanField(default=False, help_text='Indica si es un ítem fijo del sistema.'),
        ),
    ]
