# Generated by Django 5.0.1 on 2025-11-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_consumible_item_fijo_epp_item_fijo_stock_item_fijo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumible',
            old_name='modelo',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='consumible',
            old_name='monto',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='consumible',
            old_name='name',
            new_name='descipcion',
        ),
        migrations.RemoveField(
            model_name='consumible',
            name='unidades',
        ),
        migrations.AddField(
            model_name='consumible',
            name='unidad',
            field=models.CharField(default='UND', max_length=20),
        ),
    ]
