# Generated by Django 5.0.1 on 2025-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_rename_modelo_consumible_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumible',
            options={'ordering': ('codigo',), 'verbose_name': 'Consumible', 'verbose_name_plural': 'Consumibles'},
        ),
        migrations.AlterField(
            model_name='consumible',
            name='descipcion',
            field=models.CharField(db_column='descipcion', max_length=100),
        ),
        migrations.RenameField(
            model_name='consumible',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
