# Generated by Django 5.2.8 on 2026-03-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_consumible_options_alter_consumible_descipcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mts_ml_m2_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='mts_ml_m2_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='mts_ml_m2_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taza_pesos_dolares',
            name='utilidad_porcentaje_1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Primer porcentaje de utilidad global (0 = sin margen, muestra costo base)', max_digits=5),
        ),
        migrations.AddField(
            model_name='taza_pesos_dolares',
            name='utilidad_porcentaje_2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Segundo porcentaje de utilidad global', max_digits=5),
        ),
        migrations.AddField(
            model_name='taza_pesos_dolares',
            name='utilidad_porcentaje_3',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tercer porcentaje de utilidad global', max_digits=5),
        ),
    ]
