# Generated by Django 6.0.3 on 2026-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_logistica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarconsumo',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
